# Only for passing letsencrypt acme challenge
services:
  nginx:
    image: nginx:1.28-alpine
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./nginx/acme.conf:/etc/nginx/templates/default.conf.template
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    env_file: .env
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c '
        certbot certonly \
          --webroot -w /var/www/certbot \
          -d ${NGINX_SERVER_NAME} \
          --email ${CERTBOT_EMAIL} \
          --agree-tos \
          --non-interactive \
          --keep-until-expiring
      '